db:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: app_development
    MYSQL_USER: pos
    MYSQL_PASSWORD: db_pass

web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db